name: lcep
channels:
    - defaults
    - conda-forge
    - rapidsai
dependencies:
    - defaults::cudatoolkit=11.0.221
    - defaults::python=3.8.2
    - conda-forge::rich=9.10.0
    - conda-forge::mlflow=1.13.1
    - conda-forge::scikit-learn=0.24.1
    - conda-forge::matplotlib=3.3.4
    - pip
    - pip:
      - xgboost==1.3.3  # xgboost on Conda is not yet built with GPU support!
      - pycuda==2019.1.2
      - system-intelligence==2.0.2
      - gputil==1.4.0
