name: Publish Container to Docker Packages

# Documentation on the primary Action used here: https://github.com/marketplace/actions/publish-docker
# https://docs.github.com/en/packages/getting-started-with-github-container-registry/enabling-github-container-registry-for-your-organization

on:
  release:
      types: [published]
  push:
      branches:
        - development
jobs:
  publish_release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: mlf-core/lcep
        username: mlf-core
        password: '${{ secrets.MLF_CORE_SYNC_TOKEN}}'
        registry: ghcr.io
        tags: "latest,1.0.1"

