name: Run flake8 linting

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Check out source-code repository

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install flake8
        run: |
            pip install flake8

      - name: Lint with flake8
        run: |
            flake8 .
