name: Sync mlf-core project

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Setup Python
          uses: actions/setup-python@v1
          with:
            python-version: 3.8

        - name: Install mlf-core
          run: pip install mlf-core

        - uses: actions/checkout@v2
          with:
              fetch-depth: 0
          name: Check out source-code repository

        - uses: oleksiyrudenko/gha-git-credentials@v1
          with:
               name: 'zethson'
               email: 'lukas.heumos@posteo.net'
               actor: 'zethson'
               token: '${{ secrets.MLF_CORE_SYNC_TOKEN}}'

        - name: Sync project
          run: mlf-core sync . ${{ secrets.MLF_CORE_SYNC_TOKEN }} zethson
